name: CI

env:
  CI: true
  ARTICLES_FILENAME: articles.csv
  FEEDS_FILENAME: feeds.csv

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - name: Install Poetry
        run: pip install poetry
      - name: Install dependencies
        run: poetry install --no-root
      - name: Format code
        run: poetry run invoke format
      - name: Run tests
        run: poetry run invoke coverage
      - name: Lint
        run: poetry run invoke lint
      - name: Coverage report
        run: poetry run invoke coverage-report-xml
      - name: Coverage report to Codecov
        uses: codecov/codecov-action@v4
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
